[package]
name = "uniserve-serving"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
asynk-strim-attr.workspace = true
base64.workspace = true
easy-ext.workspace = true
enum-as-inner.workspace = true
futures.workspace = true
image.workspace = true
indexmap.workspace = true
itertools.workspace = true
llm-multimodal.workspace = true
minijinja.workspace = true
minijinja-contrib.workspace = true
openai-harmony.workspace = true
serde.workspace = true
serde-json-fmt.workspace = true
serde_json.workspace = true
serde_with.workspace = true
sha2.workspace = true
subenum.workspace = true
thiserror.workspace = true
thiserror-ext.workspace = true
tokio.workspace = true
tracing.workspace = true
trait-set.workspace = true
uuid.workspace = true
uniserve-engine-gateway.workspace = true
uniserve-core.workspace = true
uniserve-model-profile.workspace = true
xgrammar-rs.workspace = true

[dev-dependencies]
bytes.workspace = true
clap.workspace = true
expect-test.workspace = true
paste.workspace = true
png.workspace = true
serial_test.workspace = true
tempfile.workspace = true
tracing-subscriber.workspace = true
uniserve-engine-gateway = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
