[package]
name = "uniserve-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
crossbeam-channel.workspace = true
indexmap.workspace = true
libc.workspace = true
libloading.workspace = true
nvtx.workspace = true
rustix.workspace = true
thiserror.workspace = true
uniserve-core.workspace = true
uniserve-worker-ipc.workspace = true

[lints]
workspace = true
