"""Unified forward execution interfaces."""
from __future__ import annotations

from .adapter import ForwardAdapterContext, ForwardModelAdapter, WorkerForwardAdapter
from .batch import ForwardBatchBuilder
from .deferred_text import (
    DeferredDecodeBurstSeqResult,
    DeferredTerminalDecodeBurstSeqResult,
    DeferredTextSeqResult,
)
from .descriptor import ForwardModelDescriptor, ForwardModelModules, descriptor_from_model
from .executor import ForwardExecutor
from .fallback import (
    EagerFallbackReason,
    EagerFallbackRecorder,
    EagerFallbackWarning,
    ForwardGraphPolicy,
    StrictForwardGraphError,
)
from .graph import (
    CapturedForwardGraph,
    CudaGraphForwardRunner,
    DecodeGraphProgram,
    DenoiseStepGraphProgram,
    ForwardGraphBufferRegistry,
    ForwardGraphProgram,
    ForwardGraphShapeKey,
    ForwardGraphStats,
    GraphEligibility,
    PackedVisibleGraphProgram,
    PaddingPolicy,
    PrefillGraphProgram,
    SlotAxis,
    graph_shape_key,
)
from .plan import (
    CacheSpanPlan,
    ForwardAdmissionDecision,
    ForwardAdmissionRouter,
    ForwardModality,
    ForwardOutputKind,
    ForwardOutputSlot,
    ForwardPlan,
    ForwardPlanBuilder,
    ForwardPostprocessPolicy,
    ForwardResultProjection,
    ForwardRowPlan,
    ForwardRuntimeHandles,
    ForwardSegmentClass,
    ForwardSegmentPlan,
    ForwardShapeSummary,
    KvWritePolicy,
    Route,
    TextTokenSpanPlan,
)
from .postprocess import ForwardPostprocessor
from .result import (
    CommitNeuralResult,
    DenoiseBranchKey,
    DenoisePostprocessEntry,
    DenoiseVelocityResult,
    EncodeResult,
    ForwardGraphExecutionInfo,
    ForwardResult,
    TextLogitsResult,
    TextPostprocessEntry,
)
from .runner import EagerForwardRunner, ForwardRunner
from .step import ForwardGroupPlanner, ForwardStepExecutor, ForwardStepOptions
from .stream import (
    ForwardGraphPagedKVView,
    ForwardGraphStreamState,
    ForwardPagedKVSegment,
    ForwardPagedKVView,
    ForwardSegmentSpec,
    ForwardStream,
    ForwardStreamBuilder,
    SegmentClass,
    SegmentClassId,
    SegmentModality,
    SegmentModalityId,
    VisiblePolicy,
    VisiblePolicyKind,
    build_text_position_indexes,
)

__all__ = [
    "CacheSpanPlan",
    "CapturedForwardGraph",
    "CommitNeuralResult",
    "CudaGraphForwardRunner",
    "DecodeGraphProgram",
    "DeferredDecodeBurstSeqResult",
    "DeferredTerminalDecodeBurstSeqResult",
    "DeferredTextSeqResult",
    "DenoiseBranchKey",
    "DenoisePostprocessEntry",
    "DenoiseStepGraphProgram",
    "DenoiseVelocityResult",
    "EagerFallbackReason",
    "EagerFallbackRecorder",
    "EagerFallbackWarning",
    "EagerForwardRunner",
    "EncodeResult",
    "ForwardAdapterContext",
    "ForwardAdmissionDecision",
    "ForwardAdmissionRouter",
    "ForwardBatchBuilder",
    "ForwardExecutor",
    "ForwardGraphBufferRegistry",
    "ForwardGraphExecutionInfo",
    "ForwardGraphPagedKVView",
    "ForwardGraphPolicy",
    "ForwardGraphProgram",
    "ForwardGraphShapeKey",
    "ForwardGraphStreamState",
    "ForwardGraphStats",
    "ForwardGroupPlanner",
    "ForwardModality",
    "ForwardModelAdapter",
    "ForwardModelDescriptor",
    "ForwardModelModules",
    "ForwardOutputKind",
    "ForwardOutputSlot",
    "ForwardPagedKVSegment",
    "ForwardPagedKVView",
    "ForwardPlan",
    "ForwardPlanBuilder",
    "ForwardPostprocessPolicy",
    "ForwardPostprocessor",
    "ForwardResult",
    "ForwardResultProjection",
    "ForwardRowPlan",
    "ForwardRunner",
    "ForwardRuntimeHandles",
    "ForwardSegmentSpec",
    "ForwardSegmentClass",
    "ForwardSegmentPlan",
    "ForwardShapeSummary",
    "ForwardStepExecutor",
    "ForwardStepOptions",
    "ForwardStream",
    "ForwardStreamBuilder",
    "GraphEligibility",
    "KvWritePolicy",
    "PackedVisibleGraphProgram",
    "PaddingPolicy",
    "PrefillGraphProgram",
    "Route",
    "SegmentClass",
    "SegmentClassId",
    "SegmentModality",
    "SegmentModalityId",
    "SlotAxis",
    "StrictForwardGraphError",
    "TextLogitsResult",
    "TextPostprocessEntry",
    "TextTokenSpanPlan",
    "VisiblePolicy",
    "VisiblePolicyKind",
    "WorkerForwardAdapter",
    "build_text_position_indexes",
    "descriptor_from_model",
    "graph_shape_key",
]
