[package]
name = "uniserve-model-assets"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
hf-hub.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
thiserror.workspace = true
thiserror-ext.workspace = true
uniserve-config.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio.workspace = true
uniserve-tokenizer.workspace = true

[lints]
workspace = true
