[package]
name = "uniserve-server-http"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
asynk-strim-attr.workspace = true
axum.workspace = true
futures.workspace = true
http-body.workspace = true
itertools.workspace = true
libc.workspace = true
rmpv.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
socket2.workspace = true
thiserror-ext.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tonic.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-futures.workspace = true
uniserve-chat.workspace = true
uniserve-config.workspace = true
uniserve-core.workspace = true
uniserve-engine-client.workspace = true
uniserve-llm.workspace = true
uniserve-native-api.workspace = true
uniserve-observability.workspace = true
uniserve-openai-api.workspace = true
uniserve-openai-types.workspace = true
uniserve-server-app.workspace = true
uniserve-server-grpc.workspace = true
uniserve-text.workspace = true
uuid.workspace = true
validator.workspace = true

[dev-dependencies]
async-openai = { workspace = true, features = ["full"] }
bytes.workspace = true
expect-test.workspace = true
serial_test.workspace = true
tower.workspace = true
uniserve-chat.workspace = true
uniserve-chat-template.workspace = true
uniserve-engine-client = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
