[package]
name = "uniserve-engine-process"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
rmpv.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
zeromq.workspace = true
uniserve-core.workspace = true
uniserve-engine-runtime.workspace = true
uniserve-engine-wire.workspace = true
uniserve-scheduler.workspace = true
uniserve-sim.workspace = true

[dev-dependencies]
futures.workspace = true
tracing-subscriber.workspace = true
uniserve-engine-client.workspace = true

[lints]
workspace = true
