[package]
name = "uniserve-engine-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
crossbeam-channel.workspace = true
rmpv.workspace = true
serde.workspace = true
thiserror-ext.workspace = true
tokio = { workspace = true, features = ["rt", "sync", "macros", "time"] }
tokio-util.workspace = true
tracing.workspace = true

uniserve-engine-api.workspace = true
uniserve-executor.workspace = true
uniserve-scheduler.workspace = true
uniserve-core.workspace = true
uniserve-worker-wire.workspace = true
uniserve-worker-ipc.workspace = true

[dev-dependencies]
futures.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing-subscriber.workspace = true

[lints]
workspace = true
