"""Measure the MiniMax-H3 trajectory tolerance envelope.

The trajectory thresholds of the validation protocol come from independent
evidence: the deviation between two equally valid attention kernels of the
same reference on identical inputs and noise. This script compares the
canonical diffusers reference (DiT attention on PyTorch SDPA's cuDNN kernel)
with the same reference on PyTorch SDPA's flash kernel, both generated by
``diffusers_reference.py`` for base t2va 16:9 5 s with the flash run
replaying the canonical run's noise, for every seed present. When a repeat of
the canonical run exists (``reference/diffusers_repeat``), it also reports
the run-to-run deviation of the canonical kernel.

Writes ``<output>/envelope.json``: the full per-pair metrics of
``trajectory_metrics.py`` and an ``envelope`` object with the worst value of
every metric over the kernel pairs (maximum for relative L2, minimum for
PSNR, SSIM and spectral cosine) and ``envelope_per_step`` with the
elementwise maximum of every per-step relative L2 curve.

Usage: ``tolerance_envelope.py --output artifacts/minimax_h3``.
"""

import argparse
import json
import math
from pathlib import Path

from trajectory_metrics import compare, summarize

WORKLOAD = "t2va_16x9_5s"
CANONICAL = "diffusers"
KERNEL_VARIANT = "diffusers_sdpa_flash"
REPEAT = "diffusers_repeat"

# Metrics where a larger value is closer agreement.
HIGHER_IS_BETTER = ("psnr", "ssim", "cosine")


def _finite(value):
    """Strict JSON: non-finite floats (identical runs' PSNR) as strings."""
    if isinstance(value, dict):
        return {key: _finite(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_finite(item) for item in value]
    if isinstance(value, float) and not math.isfinite(value):
        return str(value)
    return value


def worst(summaries: list[dict]) -> dict:
    """Return the worst value of every numeric metric over the pairs."""
    envelope = {}
    for key in summaries[0]:
        values = [s[key] for s in summaries if isinstance(s.get(key), float)]
        if not values:
            continue
        if any(token in key for token in HIGHER_IS_BETTER):
            envelope[key] = min(values)
        else:
            envelope[key] = max(values)
    return envelope


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    reference = args.output / "reference"
    pairs = {}
    for seed_dir in sorted((reference / CANONICAL / WORKLOAD).glob("seed*")):
        variant = reference / KERNEL_VARIANT / WORKLOAD / seed_dir.name
        if (variant / "metadata.json").exists():
            pairs[f"cudnn_vs_flash/{seed_dir.name}"] = compare(
                seed_dir, variant
            )
        repeat = reference / REPEAT / WORKLOAD / seed_dir.name
        if (repeat / "metadata.json").exists():
            pairs[f"cudnn_repeat/{seed_dir.name}"] = compare(seed_dir, repeat)
    if not any(name.startswith("cudnn_vs_flash") for name in pairs):
        raise SystemExit("no cuDNN/flash pair found")

    summaries = {name: summarize(result) for name, result in pairs.items()}
    kernel = [s for n, s in summaries.items() if n.startswith("cudnn_vs")]
    # Per-step curves: the elementwise maximum over the kernel pairs.
    kernel_pairs = [r for n, r in pairs.items() if n.startswith("cudnn_vs")]
    per_step = {
        key: [max(values) for values in zip(*(r[key] for r in kernel_pairs))]
        for key, value in kernel_pairs[0].items()
        if isinstance(value, list)
    }
    document = {
        "workload": WORKLOAD,
        "kernels": {
            "reference": "PyTorch SDPA cuDNN (diffusers _native_cudnn)",
            "candidate": "PyTorch SDPA flash (diffusers _native_flash)",
        },
        "pairs": pairs,
        "summaries": summaries,
        "envelope": worst(kernel),
        "envelope_per_step": per_step,
    }
    text = json.dumps(_finite(document), indent=2, allow_nan=False)
    (args.output / "envelope.json").write_text(text + "\n")
    for name, summary in summaries.items():
        print(name)
        for key, value in summary.items():
            if isinstance(value, float) and not math.isnan(value):
                print(f"  {key}: {value:.6g}")
            else:
                print(f"  {key}: {value}")


if __name__ == "__main__":
    main()
