[package]
name = "uniserve-engine-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
test-util = []

[dependencies]
anyhow.workspace = true
arc-swap.workspace = true
bytes.workspace = true
futures.workspace = true
hex.workspace = true
parking_lot.workspace = true
rmpv.workspace = true
serde.workspace = true
task-local.workspace = true
thiserror.workspace = true
thiserror-ext.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
zeromq.workspace = true

uniserve-engine-wire.workspace = true
uniserve-observability.workspace = true
uniserve-engine-api.workspace = true
uniserve-core.workspace = true
uniserve-worker-wire.workspace = true

[dev-dependencies]
bytes.workspace = true
expect-test.workspace = true
zeromq.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "time"] }

[lints]
workspace = true
