[package]
name = "uniserve-protocol-adapters"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
asynk-strim-attr.workspace = true
axum.workspace = true
futures.workspace = true
itertools.workspace = true
serde_json.workspace = true
thiserror-ext.workspace = true
tracing.workspace = true
uniserve-openai-types.workspace = true
uniserve-serving.workspace = true

[dev-dependencies]
expect-test.workspace = true
llm-multimodal.workspace = true
tokio.workspace = true

[lints]
workspace = true
