[package]
name = "uniserve-chat-output"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
asynk-strim-attr.workspace = true
futures.workspace = true
openai-harmony.workspace = true
serde_with.workspace = true
serde_json.workspace = true
subenum.workspace = true
thiserror.workspace = true
thiserror-ext.workspace = true
tokio.workspace = true
tracing.workspace = true
trait-set.workspace = true
uuid.workspace = true
uniserve-chat-protocol.workspace = true
uniserve-llm.workspace = true
uniserve-reasoning-parser.workspace = true
uniserve-text.workspace = true
uniserve-tokenizer.workspace = true
uniserve-tool-parser.workspace = true

[dev-dependencies]
expect-test.workspace = true
serial_test.workspace = true

[lints]
workspace = true
