"""Chat replies generated by block diffusion on the published checkpoints.

Each precision's DiffusionGemma checkpoint is served by ``uniserve serve``
on one GPU with its default flags and answers ``POST /v1/chat/completions``
end to end: the server renders the Gemma-4 chat template, the engine
prefills the prompt and denoises the reply canvas by canvas, committing
each finished canvas to the context, and the Gemma-4 parsers split the
thought channel and tool calls. The tests check what a client observes:

- a seeded reply streams exactly what the same request returns in one
  response, with usage, and ends at an end-of-sequence token;
- a stop string ends the reply at the string, and ``max_completion_tokens``
  truncates it inside a canvas;
- a seed draws the same reply whether its request runs alone or with
  others;
- ``chat_template_kwargs.enable_thinking`` opens and closes the thought
  channel, a tool call parses into ``tool_calls``, and an attached image is
  read;
- token-sampling controls are refused with 400.

The checkpoint directories come from ``UNISERVE_DIFFUSION_GEMMA_MODEL``
(BF16) and ``UNISERVE_DIFFUSION_GEMMA_NVFP4_MODEL`` (NVFP4). The worker
interpreter is ``UNISERVE_WORKER_PYTHON``, else the repository's
``.venv/bin/python``.
"""

from __future__ import annotations

import base64
import concurrent.futures
import io
import json
import os
from collections.abc import Iterator
from pathlib import Path

import httpx
import pytest
from PIL import Image

from tests.python.e2e.http_helpers import (
    find_free_port,
    require_uniserve_binary,
    server_process,
)

pytestmark = [
    pytest.mark.e2e,
    pytest.mark.gpu,
    pytest.mark.model("diffusion_gemma"),
]

SERVED_MODEL = "diffusion-gemma"
CHECKPOINTS = {
    "bf16": "UNISERVE_DIFFUSION_GEMMA_MODEL",
    "nvfp4": "UNISERVE_DIFFUSION_GEMMA_NVFP4_MODEL",
}
APPLES = (
    "A shop has 17 apples and sells 8, then receives 6. "
    "How many apples does it have?"
)
STORY = "Write a 300-word story about a lighthouse keeper."


def _checkpoint(precision: str) -> Path:
    variable = CHECKPOINTS[precision]
    value = os.environ.get(variable)
    if not value:
        pytest.fail(f"{variable} is required for the DiffusionGemma GPU gate")
    path = Path(value)
    if not path.is_dir():
        pytest.fail(f"configured checkpoint directory is missing: {path}")
    return path


@pytest.fixture(scope="module", params=sorted(CHECKPOINTS))
def served(request, tmp_path_factory) -> Iterator[str]:
    """Serve one precision's checkpoint with default flags; yield its URL."""
    checkpoint = _checkpoint(request.param)
    try:
        binary = require_uniserve_binary()
    except FileNotFoundError as error:
        pytest.fail(str(error))
    port = find_free_port()
    base_url = f"http://127.0.0.1:{port}"
    python = os.environ.get(
        "UNISERVE_WORKER_PYTHON", str(Path.cwd() / ".venv" / "bin" / "python")
    )
    args = [
        str(binary),
        "serve",
        str(checkpoint),
        "--served-model-name",
        SERVED_MODEL,
        "--host",
        "127.0.0.1",
        "--port",
        str(port),
        "--worker-python",
        python,
        "--max-model-len",
        "8192",
    ]
    log = tmp_path_factory.mktemp(request.param) / "server.log"
    with server_process(args, base_url, log, timeout_s=1800.0):
        yield base_url


def _body(content, **fields) -> dict:
    return {
        "model": SERVED_MODEL,
        "messages": [{"role": "user", "content": content}],
        "max_completion_tokens": 512,
        **fields,
    }


def _complete(base_url: str, body: dict) -> dict:
    response = httpx.post(
        f"{base_url}/v1/chat/completions", json=body, timeout=600.0
    )
    assert response.status_code == 200, response.text
    return response.json()


def _stream(base_url: str, body: dict) -> list[dict]:
    """The chunks of one streamed reply, without the closing marker."""
    chunks = []
    with httpx.stream(
        "POST",
        f"{base_url}/v1/chat/completions",
        json={**body, "stream": True},
        timeout=600.0,
    ) as response:
        assert response.status_code == 200, response.read()
        for line in response.iter_lines():
            if not line.startswith("data: ") or line == "data: [DONE]":
                continue
            chunks.append(json.loads(line.removeprefix("data: ")))
    return chunks


def _thinking(enabled: bool) -> dict:
    return {"chat_template_kwargs": {"enable_thinking": enabled}}


def test_a_streamed_reply_equals_the_complete_reply(served):
    """One seed's reply streams as it completes, with usage, ending at EOS."""
    body = _body(APPLES, seed=20260927, **_thinking(True))
    complete = _complete(served, body)
    chunks = _stream(
        served, {**body, "stream_options": {"include_usage": True}}
    )

    (choice,) = complete["choices"]
    assert choice["finish_reason"] == "stop"
    assert complete["usage"]["completion_tokens"] < 512
    assert "15" in choice["message"]["content"]

    deltas = [
        chunk["choices"][0]["delta"] for chunk in chunks if chunk["choices"]
    ]
    content = "".join(delta.get("content") or "" for delta in deltas)
    reasoning = "".join(
        delta.get("reasoning_content") or "" for delta in deltas
    )
    assert content == choice["message"]["content"]
    assert reasoning == choice["message"]["reasoning_content"]
    finishes = [
        chunk["choices"][0]["finish_reason"]
        for chunk in chunks
        if chunk["choices"] and chunk["choices"][0].get("finish_reason")
    ]
    assert finishes == ["stop"]
    assert chunks[-1]["usage"] == complete["usage"]


def test_a_stop_string_ends_the_reply(served):
    """The reply ends before the first occurrence of a stop string.

    Stop strings match the decoded reply, special tokens included, so the
    stop is two words of the visible story, which no channel markup holds.
    """
    body = _body(STORY, seed=5)
    reply = _complete(served, body)["choices"][0]["message"]["content"]
    words = reply.split()
    stop = " ".join(words[len(words) // 2 : len(words) // 2 + 2])

    stopped = _complete(served, {**body, "stop": [stop]})
    (choice,) = stopped["choices"]
    assert choice["finish_reason"] == "stop"
    assert choice["message"]["content"] == reply[: reply.index(stop)]


def test_the_completion_limit_truncates_inside_a_canvas(served):
    """A limit inside a canvas truncates the reply at exactly that many."""
    reply = _complete(served, _body(STORY, seed=5, max_completion_tokens=100))
    assert reply["choices"][0]["finish_reason"] == "length"
    assert reply["usage"]["completion_tokens"] == 100


def test_a_seed_draws_the_same_reply_alone_and_in_a_batch(served):
    """The seed alone decides the reply, whatever runs beside it."""
    body = _body(APPLES, seed=77, **_thinking(True))
    alone = _complete(served, body)["choices"][0]["message"]

    others = [
        _body(STORY, seed=seed, max_completion_tokens=300) for seed in (1, 2, 3)
    ]
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as pool:
        futures = [pool.submit(_complete, served, other) for other in others]
        batched = pool.submit(_complete, served, body).result()
        for future in futures:
            future.result()
    assert batched["choices"][0]["message"] == alone


def test_thinking_opens_and_closes_the_thought_channel(served):
    """With thinking the reply reasons first; without it, it does not."""
    thinking = _complete(served, _body(APPLES, seed=3, **_thinking(True)))
    direct = _complete(served, _body(APPLES, seed=3, **_thinking(False)))

    assert thinking["choices"][0]["message"]["reasoning_content"]
    assert not direct["choices"][0]["message"].get("reasoning_content")
    for reply in (thinking, direct):
        assert "15" in reply["choices"][0]["message"]["content"]


def test_a_tool_call_is_returned_as_a_call(served):
    """A reply that calls a declared tool returns the call with arguments.

    The model does not write a well-formed call for every seed (it may omit
    the call's opening token or leave the thought channel open, which the
    checkpoint's own response parser does not read as a call either), so
    the request is drawn with a few seeds and every call returned must be
    the right one, at least one reply returning it.
    """
    tool = {
        "type": "function",
        "function": {
            "name": "get_weather",
            "description": "Get the current weather for a city.",
            "parameters": {
                "type": "object",
                "properties": {"city": {"type": "string"}},
                "required": ["city"],
            },
        },
    }
    calls = []
    for seed in range(9, 13):
        reply = _complete(
            served,
            _body(
                "What is the weather in Paris right now?",
                seed=seed,
                tools=[tool],
            ),
        )
        (choice,) = reply["choices"]
        returned = choice["message"].get("tool_calls") or []
        assert (choice["finish_reason"] == "tool_calls") == bool(returned)
        calls.extend(returned)
    assert calls
    for call in calls:
        assert call["function"]["name"] == "get_weather"
        assert json.loads(call["function"]["arguments"])["city"] == "Paris"


def test_an_attached_image_is_read(served):
    """The reply names the color of a solid image in the message."""
    buffer = io.BytesIO()
    Image.new("RGB", (224, 224), (220, 30, 30)).save(buffer, "PNG")
    source = "data:image/png;base64," + base64.b64encode(
        buffer.getvalue()
    ).decode("ascii")
    reply = _complete(
        served,
        {
            "model": SERVED_MODEL,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {"type": "image_url", "image_url": {"url": source}},
                        {
                            "type": "text",
                            "text": "Name this image's color in one word.",
                        },
                    ],
                }
            ],
            "max_completion_tokens": 256,
            "seed": 4,
        },
    )
    assert "red" in reply["choices"][0]["message"]["content"].lower()


@pytest.mark.parametrize(
    ("control", "value"),
    [("temperature", 0.7), ("top_p", 0.9), ("logprobs", True)],
)
def test_token_sampling_controls_are_refused(served, control, value):
    """A control that has no meaning for a canvas is a 400 naming it."""
    response = httpx.post(
        f"{served}/v1/chat/completions",
        json=_body(APPLES, **{control: value}),
        timeout=60.0,
    )
    assert response.status_code == 400
    assert control in response.json()["error"]["message"]
