from typing import Any

class Server:
    def __init__(
        self,
        service_name: str,
        max_payload: int = 1_048_576,
        max_inflight: int = 1,
    ) -> None: ...
    def recv(self) -> Any: ...
    def try_recv(self) -> Any | None: ...
    def respond(self, response: Any) -> None: ...
