[package]
name = "uniserve-engine-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arc-swap.workspace = true
bytes.workspace = true
futures.workspace = true
hex.workspace = true
parking_lot.workspace = true
task-local.workspace = true
thiserror.workspace = true
thiserror-ext.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
zeromq.workspace = true
uniserve-core.workspace = true
uniserve-engine-api.workspace = true
uniserve-engine-wire.workspace = true
uniserve-observability.workspace = true

[dev-dependencies]

[lints]
workspace = true
