[package]
name = "uniserve-worker-ipc-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
iceoryx2.workspace = true
iceoryx2-bb-elementary-traits.workspace = true
tracing.workspace = true
uniserve-worker-wire.workspace = true

[lints]
workspace = true
